import {
  Capability,
  Deployment,
  Workload,
  SystemMetadata,
} from './types'

export const systemMetadata: SystemMetadata = {
  version: 'v1.0.0',
  uptime: '99.998%',
  region: 'blr-south-1',
  lastDeploy: '2026-01-06',
  status: 'healthy',
  deploymentSuccess: '100%',
  mttr: '12m',
  activeServices: 2,
}

export const capabilities: Capability[] = [
  // Languages
  {
    id: 'python',
    name: 'Python',
    category: 'language',
    tier: 'core',
    confidence: 95,
    status: 'healthy',
    lastUpdated: '2024-01-06',
  },
  {
    id: 'bash',
    name: 'Bash',
    category: 'language',
    tier: 'core',
    confidence: 92,
    status: 'healthy',
    lastUpdated: '2024-01-06',
  },
  {
    id: 'sql',
    name: 'SQL',
    category: 'language',
    tier: 'core',
    confidence: 90,
    status: 'healthy',
    lastUpdated: '2024-01-05',
  },
  {
    id: 'cpp',
    name: 'C/C++',
    category: 'language',
    tier: 'reliable',
    confidence: 75,
    status: 'healthy',
    lastUpdated: '2023-06-15',
  },
  // Infrastructure
  {
    id: 'terraform',
    name: 'Terraform',
    category: 'infra',
    tier: 'core',
    confidence: 88,
    status: 'healthy',
    lastUpdated: '2024-01-04',
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    category: 'infra',
    tier: 'reliable',
    confidence: 70,
    status: 'healthy',
    lastUpdated: '2023-12-20',
  },
  {
    id: 'docker',
    name: 'Docker',
    category: 'infra',
    tier: 'core',
    confidence: 92,
    status: 'healthy',
    lastUpdated: '2024-01-02',
  },
  {
    id: 'ansible',
    name: 'Ansible',
    category: 'infra',
    tier: 'reliable',
    confidence: 85,
    status: 'healthy',
    lastUpdated: '2023-11-30',
  },
  {
    id: 'linux',
    name: 'Linux',
    category: 'os',
    tier: 'core',
    confidence: 96,
    status: 'healthy',
    lastUpdated: '2024-01-06',
  },
  // Networking
  {
    id: 'nginx',
    name: 'NGINX',
    category: 'infra',
    tier: 'core',
    confidence: 94,
    status: 'healthy',
    lastUpdated: '2024-01-06',
  },
  {
    id: 'haproxy',
    name: 'HAProxy',
    category: 'infra',
    tier: 'reliable',
    confidence: 88,
    status: 'healthy',
    lastUpdated: '2023-12-15',
  },
  {
    id: 'tinyproxy',
    name: 'TinyProxy / Traffic Server',
    category: 'infra',
    tier: 'reliable',
    confidence: 85,
    status: 'healthy',
    lastUpdated: '2024-01-01',
  },
  // Databases
  {
    id: 'mysql',
    name: 'MySQL',
    category: 'database',
    tier: 'core',
    confidence: 93,
    status: 'healthy',
    lastUpdated: '2024-01-05',
  },
  {
    id: 'mariadb',
    name: 'MariaDB (Galera)',
    category: 'database',
    tier: 'core',
    confidence: 91,
    status: 'healthy',
    lastUpdated: '2024-01-03',
  },
  {
    id: 'elasticsearch',
    name: 'Elasticsearch',
    category: 'database',
    tier: 'reliable',
    confidence: 85,
    status: 'healthy',
    lastUpdated: '2024-01-02',
  },
  {
    id: 'aerospike',
    name: 'Aerospike',
    category: 'database',
    tier: 'reliable',
    confidence: 80,
    status: 'healthy',
    lastUpdated: '2023-12-10',
  },
  {
    id: 'rabbitmq',
    name: 'RabbitMQ',
    category: 'database',
    tier: 'reliable',
    confidence: 82,
    status: 'healthy',
    lastUpdated: '2023-11-20',
  },
  // Observability
  {
    id: 'prometheus',
    name: 'Prometheus',
    category: 'observability',
    tier: 'core',
    confidence: 94,
    status: 'healthy',
    lastUpdated: '2024-01-06',
  },
  {
    id: 'grafana',
    name: 'Grafana',
    category: 'observability',
    tier: 'core',
    confidence: 93,
    status: 'healthy',
    lastUpdated: '2024-01-06',
  },
  {
    id: 'influxdb',
    name: 'InfluxDB',
    category: 'observability',
    tier: 'reliable',
    confidence: 86,
    status: 'healthy',
    lastUpdated: '2023-12-20',
  },
  {
    id: 'kibana',
    name: 'Kibana',
    category: 'observability',
    tier: 'reliable',
    confidence: 85,
    status: 'healthy',
    lastUpdated: '2024-01-02',
  },
  // Backend
  {
    id: 'django',
    name: 'Django REST',
    category: 'backend',
    tier: 'reliable',
    confidence: 87,
    status: 'healthy',
    lastUpdated: '2023-06-30',
  },
  {
    id: 'osquery',
    name: 'osquery',
    category: 'observability',
    tier: 'reliable',
    confidence: 84,
    status: 'healthy',
    lastUpdated: '2024-01-02',
  },
]

export const deployments: Deployment[] = [
  {
    id: 'phonpe-sre-current',
    company: 'PhonePe',
    role: 'Site Reliability Engineer',
    period: 'Jul 2023 - Present',
    startDate: '2023-07-01',
    endDate: null,
    status: 'stable',
    impact: [
      'Owned reliability for 50+ production distributed systems',
      'Reduced MTTR by ~25% through root cause fixes',
      'GitLab CI/CD-driven NGINX configuration deployments',
      'Automated critical database operations (Python, MySQL, Bash)',
      'Managed TinyProxy/HAProxy infrastructure',
      'Defined and tracked SLIs/SLOs, led incident response',
    ],
    technologies: [
      'Prometheus',
      'Grafana',
      'InfluxDB',
      'Terraform',
      'NGINX',
      'HAProxy',
      'Python',
      'MySQL',
      'MariaDB',
      'Docker',
    ],
  },
  {
    id: 'phonpe-sre-intern',
    company: 'PhonePe',
    role: 'Site Reliability Engineer Intern',
    period: 'Feb 2023 - Jun 2023',
    startDate: '2023-02-01',
    endDate: '2023-06-30',
    status: 'completed',
    impact: [
      'Developed Django REST API for on-call roster management',
      'Deployed multi-master MariaDB Galera cluster',
      'Configured NGINX with Keepalived for HA',
      'Designed end-to-end observability with Prometheus & Grafana',
    ],
    technologies: [
      'Django',
      'MariaDB',
      'NGINX',
      'Prometheus',
      'Grafana',
      'Keepalived',
      'Python',
    ],
  },
  {
    id: 'airbus-intern',
    company: 'Airbus',
    role: 'Software Development Engineer Intern',
    period: 'May 2022 - Jun 2022',
    startDate: '2022-05-01',
    endDate: '2022-06-30',
    status: 'archived',
    impact: [
      'Enhanced system performance by 25% using C data structures',
      'Implemented custom network protocols with skip lists',
      'Reduced request response times from O(n) to O(log n)',
    ],
    technologies: ['C', 'Network Protocols', 'Data Structures'],
  },
]

export const workloads: Workload[] = [
  {
    id: 'hostsdb',
    name: 'HostsDB',
    description: 'Infrastructure Inventory & Monitoring',
    longDescription:
      'Comprehensive system-level monitoring tool leveraging osquery for metrics collection with Elasticsearch and Kibana visualization.',
    version: '1.2.0',
    health: 'healthy',
    status: 'active',
    uptime: '99.8%',
    lastUpdated: '2024-01-02',
    stack: ['osquery', 'Python', 'Elasticsearch', 'Kibana'],
    repo: 'https://github.com/garvitjoshi007/hostsdb',
  },
  {
    id: 'evicta',
    name: 'Evicta',
    description: 'Semantic Inference Cache Engine',
    longDescription:
      'High-performance inference cache enabling deterministic semantic reuse of LLM responses with intent normalization, subject-aware routing, and LRU eviction.',
    version: '2.1.0',
    health: 'experimental',
    status: 'maintained',
    uptime: '99.5%',
    lastUpdated: '2024-01-05',
    stack: ['Python', 'LLM', 'Caching', 'Semantic Search'],
    repo: 'https://github.com/garvitjoshi007/evicta',
  },
]
